// ═══════════════════════════════════════════════════════════
//  COMPATIBILITY ANALYSIS ENGINE — 合婚分析
// ═══════════════════════════════════════════════════════════

import {
  ELEMENTS,
  generates,
  controls,
  generatedBy,
  controlledBy,
  type BaziResult,
} from '@/lib/bazi';

// ── Branch Interaction Tables ──────────────────────────────

export const SIX_HARMONY: [string, string][] = [
  ['子', '丑'], ['寅', '亥'], ['卯', '戌'], ['辰', '酉'], ['巳', '申'], ['午', '未'],
];

export const SIX_CLASH: [string, string][] = [
  ['子', '午'], ['丑', '未'], ['寅', '申'], ['卯', '酉'], ['辰', '戌'], ['巳', '亥'],
];

// ── Types ──────────────────────────────────────────────────

export type BranchInteraction = 'six_harmony' | 'six_clash' | 'neutral';

export type DayMasterRelationship =
  | 'generates'
  | 'generated_by'
  | 'controls'
  | 'controlled_by'
  | 'same';

export type CompatibilityTier = '上等' | '中上' | '中等' | '需注意';

export type ElementBalance = {
  counts: Record<string, number>;
  missing: string[];
  dominant: string[];
};

// ── Branch Interaction ─────────────────────────────────────

export function getBranchInteraction(
  branchA: string,
  branchB: string,
): BranchInteraction {
  for (const [x, y] of SIX_HARMONY) {
    if ((branchA === x && branchB === y) || (branchA === y && branchB === x)) {
      return 'six_harmony';
    }
  }
  for (const [x, y] of SIX_CLASH) {
    if ((branchA === x && branchB === y) || (branchA === y && branchB === x)) {
      return 'six_clash';
    }
  }
  return 'neutral';
}

// ── Day Master Element Relationship ───────────────────────
// Returns the relationship of elemA relative to elemB (from A's perspective).
// Covers all 25 combinations (5×5) with no unhandled case:
//   same         : A and B share the same element
//   generates    : A generates B
//   generated_by : A is generated by B
//   controls     : A controls B
//   controlled_by: A is controlled by B

export function getDayMasterRelationship(
  elemA: string,
  elemB: string,
): DayMasterRelationship {
  if (elemA === elemB)               return 'same';
  if (generates(elemA) === elemB)    return 'generates';
  if (generatedBy(elemA) === elemB)  return 'generated_by';
  if (controls(elemA) === elemB)     return 'controls';
  return 'controlled_by'; // only remaining case: controlledBy(elemA) === elemB
}

// ── Overall Rating Tier ────────────────────────────────────
// Priority order (first match wins):
//   需注意 : any negative signal (six_clash OR 相克)
//   上等   : both positive (six_harmony AND 相生)
//   中上   : exactly one positive condition met
//   中等   : both neutral (no positive, no negative)

export function computeCompatibilityTier(
  branchInteraction: BranchInteraction,
  dmRelationship: DayMasterRelationship,
): CompatibilityTier {
  const isNegativeBranch = branchInteraction === 'six_clash';
  const isNegativeDM     = dmRelationship === 'controls' || dmRelationship === 'controlled_by';
  const isPositiveBranch = branchInteraction === 'six_harmony';
  const isPositiveDM     = dmRelationship === 'generates' || dmRelationship === 'generated_by';

  if (isNegativeBranch || isNegativeDM) return '需注意';
  if (isPositiveBranch && isPositiveDM) return '上等';
  if (isPositiveBranch || isPositiveDM) return '中上';
  return '中等';
}

// ── Element Balance ────────────────────────────────────────
// Tallies the element of every stem and branch across both persons' pillars.
// Null (unknown-time) hour pillars are skipped.

export function computeElementBalance(
  pillarsA: BaziResult['pillars'],
  pillarsB: BaziResult['pillars'],
): ElementBalance {
  const counts: Record<string, number> = {
    wood: 0, fire: 0, earth: 0, metal: 0, water: 0,
  };

  for (const pillars of [pillarsA, pillarsB] as const) {
    for (const key of ['hour', 'day', 'month', 'year'] as const) {
      const p = pillars[key];
      if (!p) continue;
      counts[p.stem.element]++;
      counts[p.branch.element]++;
    }
  }

  const missing  = ELEMENTS.filter(el => counts[el] === 0);
  const dominant = ELEMENTS.filter(el => counts[el] >= 6);

  return { counts, missing, dominant };
}
