import test from 'node:test';
import assert from 'node:assert/strict';

import {
  getBranchInteraction,
  getDayMasterRelationship,
  computeCompatibilityTier,
  computeElementBalance,
  SIX_HARMONY,
  SIX_CLASH,
} from '../src/lib/compatibility';
import { STEMS, BRANCHES, type BaziResult } from '../src/lib/bazi';

// ── Helpers ────────────────────────────────────────────────

function makePillars(
  yearStem: number, yearBranch: number,
  monthStem: number, monthBranch: number,
  dayStem: number,   dayBranch: number,
  hourStem?: number, hourBranch?: number,
): BaziResult['pillars'] {
  const p = (s: number, b: number) => ({
    stem: STEMS[s], branch: BRANCHES[b], stemIdx: s, branchIdx: b,
  });
  return {
    year:  p(yearStem, yearBranch),
    month: p(monthStem, monthBranch),
    day:   p(dayStem, dayBranch),
    hour:  hourStem !== undefined && hourBranch !== undefined
      ? p(hourStem, hourBranch)
      : null,
  };
}

// ══════════════════════════════════════════════════════════
// 1. Six Harmony / Six Clash detection
// ══════════════════════════════════════════════════════════

test('getBranchInteraction — all 6 六合 pairs, both orderings', () => {
  for (const [x, y] of SIX_HARMONY) {
    assert.equal(getBranchInteraction(x, y), 'six_harmony', `${x}+${y} should be six_harmony`);
    assert.equal(getBranchInteraction(y, x), 'six_harmony', `${y}+${x} (reversed) should be six_harmony`);
  }
});

test('getBranchInteraction — all 6 六冲 pairs, both orderings', () => {
  for (const [x, y] of SIX_CLASH) {
    assert.equal(getBranchInteraction(x, y), 'six_clash', `${x}+${y} should be six_clash`);
    assert.equal(getBranchInteraction(y, x), 'six_clash', `${y}+${x} (reversed) should be six_clash`);
  }
});

test('getBranchInteraction — neutral pair is neither harmony nor clash', () => {
  // 子(Rat) and 寅(Tiger) are not in any six-harmony or six-clash pair
  assert.equal(getBranchInteraction('子', '寅'), 'neutral');
  assert.equal(getBranchInteraction('寅', '子'), 'neutral');
});

// ══════════════════════════════════════════════════════════
// 2. Day Master relationship — all 5 categories
// ══════════════════════════════════════════════════════════

test('getDayMasterRelationship — same element', () => {
  // wood vs wood
  assert.equal(getDayMasterRelationship('wood', 'wood'), 'same');
  // fire vs fire
  assert.equal(getDayMasterRelationship('fire', 'fire'), 'same');
});

test('getDayMasterRelationship — generates (A generates B)', () => {
  // wood generates fire
  assert.equal(getDayMasterRelationship('wood', 'fire'), 'generates');
  // water generates wood
  assert.equal(getDayMasterRelationship('water', 'wood'), 'generates');
});

test('getDayMasterRelationship — generated_by (A is generated by B)', () => {
  // fire is generated by wood
  assert.equal(getDayMasterRelationship('fire', 'wood'), 'generated_by');
  // wood is generated by water
  assert.equal(getDayMasterRelationship('wood', 'water'), 'generated_by');
});

test('getDayMasterRelationship — controls (A controls B)', () => {
  // wood controls earth
  assert.equal(getDayMasterRelationship('wood', 'earth'), 'controls');
  // fire controls metal
  assert.equal(getDayMasterRelationship('fire', 'metal'), 'controls');
});

test('getDayMasterRelationship — controlled_by (A is controlled by B)', () => {
  // earth is controlled by wood
  assert.equal(getDayMasterRelationship('earth', 'wood'), 'controlled_by');
  // metal is controlled by fire
  assert.equal(getDayMasterRelationship('metal', 'fire'), 'controlled_by');
});

// ══════════════════════════════════════════════════════════
// 3. Overall Rating tier logic — all 4 tiers
// ══════════════════════════════════════════════════════════

test('computeCompatibilityTier — 上等: 六合 day branch AND 相生 day masters', () => {
  assert.equal(computeCompatibilityTier('six_harmony', 'generates'),    '上等');
  assert.equal(computeCompatibilityTier('six_harmony', 'generated_by'), '上等');
});

test('computeCompatibilityTier — 中上: one condition met, other neutral', () => {
  // six_harmony branch, same (neutral) DM
  assert.equal(computeCompatibilityTier('six_harmony', 'same'), '中上');
  // neutral branch, generates (positive) DM
  assert.equal(computeCompatibilityTier('neutral', 'generates'),    '中上');
  assert.equal(computeCompatibilityTier('neutral', 'generated_by'), '中上');
});

test('computeCompatibilityTier — 中等: both neutral (no positive, no negative)', () => {
  assert.equal(computeCompatibilityTier('neutral', 'same'), '中等');
});

test('computeCompatibilityTier — 需注意: 六冲 day branch', () => {
  assert.equal(computeCompatibilityTier('six_clash', 'same'),      '需注意');
  assert.equal(computeCompatibilityTier('six_clash', 'generates'), '需注意');
});

test('computeCompatibilityTier — 需注意: 相克 day masters', () => {
  assert.equal(computeCompatibilityTier('neutral',     'controls'),      '需注意');
  assert.equal(computeCompatibilityTier('neutral',     'controlled_by'), '需注意');
  assert.equal(computeCompatibilityTier('six_harmony', 'controls'),      '需注意');
});

// ══════════════════════════════════════════════════════════
// 4. Element balance
// ══════════════════════════════════════════════════════════

test('computeElementBalance — balanced chart (no missing, no dominant)', () => {
  // Stems: 甲(0,wood) 丙(2,fire) 戊(4,earth) 庚(6,metal) 壬(8,water) 乙(1,wood) 丁(3,fire) 己(5,earth)
  // Branches: 午(6,fire) 申(8,metal) 寅(2,wood) 子(0,water) 丑(1,earth) 酉(9,metal) 亥(11,water) 午(6,fire)
  // Combined: wood=3(甲+乙+寅), fire=3(丙+丁+午×2... wait let me recount)
  //
  // Person A pillars (no hour):
  //   year:  stem=甲(0,wood),  branch=午(6,fire)  → wood, fire
  //   month: stem=丙(2,fire),  branch=申(8,metal) → fire, metal
  //   day:   stem=壬(8,water), branch=寅(2,wood)  → water, wood
  // Person B pillars (no hour):
  //   year:  stem=乙(1,wood),  branch=丑(1,earth) → wood, earth
  //   month: stem=庚(6,metal), branch=亥(11,water)→ metal, water
  //   day:   stem=丙(2,fire),  branch=辰(4,earth) → fire, earth   ← 辰=earth idx 4
  //
  // Combined: wood=3, fire=3, earth=2, metal=2, water=2 → balanced
  const pillarsA = makePillars(
    0,  6,   // year:  甲(wood), 午(fire)
    2,  8,   // month: 丙(fire), 申(metal)
    8,  2,   // day:   壬(water), 寅(wood)
  );
  const pillarsB = makePillars(
    1,  1,   // year:  乙(wood), 丑(earth)
    6,  11,  // month: 庚(metal), 亥(water)
    2,  4,   // day:   丙(fire), 辰(earth)
  );

  const balance = computeElementBalance(pillarsA, pillarsB);
  assert.equal(balance.missing.length,  0, 'no missing elements');
  assert.equal(balance.dominant.length, 0, 'no dominant elements');
  assert.ok(balance.counts['wood']  >= 1);
  assert.ok(balance.counts['fire']  >= 1);
  assert.ok(balance.counts['earth'] >= 1);
  assert.ok(balance.counts['metal'] >= 1);
  assert.ok(balance.counts['water'] >= 1);
});

test('computeElementBalance — chart with a missing element (no metal)', () => {
  // All stems and branches chosen to exclude metal:
  //   Non-metal stems:  甲(0,wood) 乙(1,wood) 丙(2,fire) 丁(3,fire) 戊(4,earth) 己(5,earth) 壬(8,water) 癸(9,water)
  //   Non-metal branches: 子(0,water) 丑(1,earth) 寅(2,wood) 卯(3,wood) 辰(4,earth) 巳(5,fire) 午(6,fire) 未(7,earth) 戌(10,earth) 亥(11,water)
  //
  // Person A: year=甲子, month=丙寅, day=戊午  → wood,water | fire,wood | earth,fire
  // Person B: year=癸丑, month=乙亥, day=丁未  → water,earth | wood,water | fire,earth
  const pillarsA = makePillars(0, 0, 2, 2, 4, 6);   // 甲子 丙寅 戊午
  const pillarsB = makePillars(9, 1, 1, 11, 3, 7);  // 癸丑 乙亥 丁未

  const balance = computeElementBalance(pillarsA, pillarsB);
  assert.ok(balance.missing.includes('metal'), 'metal should be missing');
  assert.equal(balance.counts['metal'], 0);
});

test('computeElementBalance — chart with a dominant element (water >= 6)', () => {
  // Person A: all-water pillars (no hour)
  //   year=壬子, month=癸亥, day=壬子 → water×6
  // Person B: mixed (just needs to be valid)
  //   year=甲午, month=戊申, day=丙丑
  const pillarsA = makePillars(
    8,  0,   // year:  壬(water), 子(water)
    9,  11,  // month: 癸(water), 亥(water)
    8,  0,   // day:   壬(water), 子(water)
  );
  const pillarsB = makePillars(
    0,  6,   // year:  甲(wood), 午(fire)
    4,  8,   // month: 戊(earth), 申(metal)
    2,  1,   // day:   丙(fire), 丑(earth)
  );

  const balance = computeElementBalance(pillarsA, pillarsB);
  assert.ok(balance.counts['water'] >= 6, 'water should be dominant');
  assert.ok(balance.dominant.includes('water'), 'water should appear in dominant list');
});
